@startuml
class Storage {
    + Store(ingredient:IIngredient) : void
    + Take(ingredientName:string) : IIngredient
    + CheckAvailable(ingredientName:string) : bool
}

IStorage <|-- Storage
@enduml
