name: "Build Twizzar"
description: "Build Twizzar on Windows 2022"
inputs:
  configuration:
    description: "The configuration to use for the build"
    required: false
    default: "Release"
  version:
    description: "The version to build"
    required: false
    default: "1.0.0"
  solution:
    description: "The solution to restore"
    required: false
    default: "Twizzar.sln"
runs:
  using: "composite"
  steps:
    - name: Build solution
      shell: pwsh
      working-directory: ./Source
      run: msbuild ${{ inputs.solution }} /p:Configuration=${{ inputs.configuration }} /p:Version=${{ inputs.version }}
