name: "Restore Twizzar"
description: "Restore Twizzar NuGet packages"
inputs:
  configuration:
    description: "The configuration to use for the build"
    required: false
    default: "Release"
runs:
  using: "composite"
  steps:
    - name: Restore NuGet packages
      shell: pwsh
      working-directory: ./Source
      run: msbuild -t:Restore Twizzar.sln /p:Configuration=${{ inputs.configuration}}
