//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twizzar.Runtime.CoreInterfaces.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesRuntime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessagesRuntime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twizzar.Runtime.CoreInterfaces.Resources.ErrorMessagesRuntime", typeof(ErrorMessagesRuntime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asked type is not a supported base type..
        /// </summary>
        public static string BaseTypesService_AskedTypeIsNotSupported {
            get {
                return ResourceManager.GetString("BaseTypesService_AskedTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size up to 8 Bytes is allowed..
        /// </summary>
        public static string BitSequenceGenerator_InvalidSize {
            get {
                return ResourceManager.GetString("BitSequenceGenerator_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be less than zero..
        /// </summary>
        public static string CanNotBeLessThanZero {
            get {
                return ResourceManager.GetString("CanNotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string cannot be mapped to a type: .
        /// </summary>
        public static string CannotResolveTypeDescription {
            get {
                return ResourceManager.GetString("CannotResolveTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the config is of the type {0} the selected constructor should be set..
        /// </summary>
        public static string ClassNode_MapParameterDescriptions_ConcreteComponentShouldHaveSelectedCtor {
            get {
                return ResourceManager.GetString("ClassNode_MapParameterDescriptions_ConcreteComponentShouldHaveSelectedCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The defined parameters need to be bigger than zero..
        /// </summary>
        public static string FloatingPointCreator_BiggerZero {
            get {
                return ResourceManager.GetString("FloatingPointCreator_BiggerZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exponent values are wrong, used exponent size is not allowed to be bigger than exponent size..
        /// </summary>
        public static string FloatingPointCreator_InvalidExponent {
            get {
                return ResourceManager.GetString("FloatingPointCreator_InvalidExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mantissa values are wrong, used mantissa size is not allowed to be bigger than mantissa size..
        /// </summary>
        public static string FloatingPointCreator_InvalidMantissa {
            get {
                return ResourceManager.GetString("FloatingPointCreator_InvalidMantissa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current byte array element is null..
        /// </summary>
        public static string Generator_CurrentByteArrayIsNull {
            get {
                return ResourceManager.GetString("Generator_CurrentByteArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of bits for the byte generator is not divisible by 8 and can not be supported..
        /// </summary>
        public static string Generator_InvalidNumberOfBits {
            get {
                return ResourceManager.GetString("Generator_InvalidNumberOfBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string cannot be a type fullname: .
        /// </summary>
        public static string InvalidTypeName {
            get {
                return ResourceManager.GetString("InvalidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A instance for the path {0} cannot be found..
        /// </summary>
        public static string ItemScope_Get_A_instance_for_the_path__0__cannot_be_found_ {
            get {
                return ResourceManager.GetString("ItemScope_Get_A_instance_for_the_path__0__cannot_be_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not assignable to available returns of Method {1}, available Method-Signatures are: 
        /// - {2}
        ///.
        /// </summary>
        public static string MemberSetupBuilder_Invalid_ReturnValue {
            get {
                return ResourceManager.GetString("MemberSetupBuilder_Invalid_ReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup can only be used for interfaces..
        /// </summary>
        public static string MemberSetupBuilder_MemberSetupBuilder_Setup_can_only_be_used_for_interfaces_ {
            get {
                return ResourceManager.GetString("MemberSetupBuilder_MemberSetupBuilder_Setup_can_only_be_used_for_interfaces_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Method with the name {0} in type {1} found. Try to use nameof for retrieving the method name of an interface..
        /// </summary>
        public static string MemberSetupBuilder_MethodName_No_Method_with_the_name_found {
            get {
                return ResourceManager.GetString("MemberSetupBuilder_MethodName_No_Method_with_the_name_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching method found for specified parameters: {0} available Method-Signatures are: 
        /// - {1}
        ///.
        /// </summary>
        public static string MemberSetupBuilder_WithParameters_No_matching_method_for_params_types {
            get {
                return ResourceManager.GetString("MemberSetupBuilder_WithParameters_No_matching_method_for_params_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not nullable..
        /// </summary>
        public static string The_type__0__is_not_nullable_ {
            get {
                return ResourceManager.GetString("The_type__0__is_not_nullable_", resourceCulture);
            }
        }
    }
}
