trigger:
    - master

jobs:
    - job: Internal_Release_Pipeline
      displayName: Internal Release Pipeline
      pool:
          vmImage: "windows-2022"
      variables:
          solutionFolder: "Source"
          solution: "Source/TwizzarInternal.sln"
          versioningScript: "Source/BuildScripts/Ci/update-vsixmanifest-version.ps1"
          buildPlatform: "Any CPU"
          buildConfiguration: "Internal"
          ignoredWarnings: 'CS1702|CS1701|\bS[0-9]{3,}|GitVersionTask'
          NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
          NUGET_RESTORE_MSBUILD_ARGS: /property:Configuration=$(buildConfiguration)
          DeployExtensionVSIX19: "false"
          DeployExtensionVSIX22: "true"

      steps:
          - checkout: self

          - task: PowerShell@2
            displayName: Rename Namespace and Assebly to TwizzarInternal
            inputs:
                filePath: 'Source\BuildScripts\Ci\rename-namespace-for-internal.ps1'
                showWarnings: true

          - task: NuGetToolInstaller@1
            inputs:
                versionSpec: "6.1.0"

          - template: Ci/git-version.yml
            parameters:
                IsInternal: "$True"
          - template: Ci/nuget-restore.yml
          - template: Ci/build.yml
          - template: Ci/publish-artifact.yml
          - template: Ci/nuget-publish.yml
          - template: Ci/publish-symbol.yml
