// <auto-generated />

using System.Collections.Immutable;
using TwizzarInternal.Fixture;
using Twizzar.Runtime.CoreInterfaces.FixtureItem.Configuration;

namespace Twizzar.Runtime.Infrastructure.Tests.DomainService
{
    partial class UserConfigurationQueryTests
    {
        private class IItemConfig16e8bBuilder : ItemBuilder<Twizzar.Runtime.CoreInterfaces.FixtureItem.Configuration.IItemConfig<Twizzar.Runtime.Infrastructure.Tests.DomainService.IMethodTest>, IItemConfig16e8bBuilderPaths>
        {
            public IItemConfig16e8bBuilder()
            {
                this.With(p => p.MemberConfigurations.Value(
                    ImmutableDictionary.Create<IMemberPath<IMethodTest>, IItemMemberConfig<IMethodTest>>()));
            }
        }
    }
}