// <auto-generated />
using Twizzar.Fixture;
using DemoCode.ExampleCode;

namespace AcceptanceCriteriaTests
{
    partial class GenericTests
    {
        private class EmptyIGenericMethodsBuilder : ItemBuilder<DemoCode.ExampleCode.IGenericMethods, IGenericMethodsd086BuilderPaths>
        {
            public EmptyIGenericMethodsBuilder()
            {
            }
        }
    }
}