# performs a build and checks the code quality

steps:
  - task: VSBuild@1
    displayName: 'Build solution $(solution)'
    inputs:
      solution: '$(solution)'
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      maximumCpuCount: 2
      vsVersion: 17.0