// <auto-generated />
using TwizzarInternal.Fixture;
using Twizzar.Design.CoreInterfaces.TestCreation;
using ViCommon.Functional;
using ViCommon.Functional.Monads.ResultMonad;

namespace Twizzar.Design.Core.Tests.Command
{
    partial class UnitTestNavigationCommandHandlerTests
    {
        private class UnitTestNavigationCommandHandlerBuilder : ItemBuilder<Twizzar.Design.Core.Command.UnitTestNavigationCommandHandler, UnitTestNavigationCommandHandlerBuilderPaths>
        {
            public UnitTestNavigationCommandHandlerBuilder()
            {
                this.With(p => p.Ctor.locationService.Stub<ILocationService>());
                this.With(p => p.Ctor.navigationService.NavigateBackAsync.Value(Result.SuccessAsync<Unit, Failure>(Unit.New)));
            }
        }
    }
}