name: Build and Test

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [main, development]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup VSTest
              uses: darenm/Setup-VSTest@v1

            - name: Restore NuGet packages
              run: msbuild -t:Restore Twizzar.sln

            - name: Build solution
              run: msbuild Twizzar.sln /p:Configuration=Release

            - name: Test
              run: dotnet test --configuration Release --no-build --no-restore --verbosity minimal --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

            - name: Install ReportGenerator
              run: dotnet tool install -g dotnet-reportgenerator-globaltool

            - name: Generate coverage report
              run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:MarkdownSummaryGithub

            - name: Add coverage report to summary
              run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
