name: Build and Test

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [main, development]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: windows-2022
        env:
            NUGET_CERT_REVOCATION_MODE: offline
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4

            - name: Prepare
              uses: ./.github/actions/prepare-twizzar

            - name: Restore
              uses: ./.github/actions/restore-twizzar
              with:
                  configuration: Release

            - name: Build
              uses: ./.github/actions/build-twizzar
              with:
                  configuration: Release
                  version: 1.0.0

            - name: Test
              uses: ./.github/actions/test-twizzar
