name: Build and Test

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [main, development]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: windows-2022
        env:
            NUGET_CERT_REVOCATION_MODE: offline
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"
                  cache: true

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup VSTest
              uses: darenm/Setup-VSTest@v1

            - uses: actions/cache@v3
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Restore NuGet packages
              run: msbuild -t:Restore Twizzar.sln /p:RestoreUseStaticGraphEvaluation=true /p:RestoreLockedMode=true /p:RestorePackagesWithLockFile=true

            - name: Build solution
              run: msbuild Twizzar.sln /p:Configuration=Release

            - name: Test
              uses: ./.github/actions/test-twizzar
