name: Build and Test

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [main, development]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup VSTest
              uses: darenm/Setup-VSTest@v1

            - name: Restore NuGet packages
              run: msbuild -t:Restore Twizzar.sln

            - name: Build solution
              run: msbuild Twizzar.sln /p:Configuration=Release

            - name: Test
              run: dotnet test --configuration Release --no-build --verbosity normal
