name: Internal Relase Build

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-pack:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: "5.x"

            - name: Rename Namespace and Assebly to TwizzarInternal
              shell: pwsh
              run: |
                  ./BuildScripts/Ci/rename-namespace-for-internal.ps1

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2

            - name: Restore dependencies
              run: dotnet restore -p:Configuration=Internal

            - name: Build
              run: dotnet build --configuration Internal --no-restore /p:Version=${{ steps.gitversion.outputs.assemblySemVer }}

            - name: Pack
              run: dotnet pack --configuration Internal --no-build --output nupkgs /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

            - name: Push to NuGet
              run: dotnet nuget push ./**/nupkgs/*.nupkg --source "https://nuget.pkg.github.com/Twizzar/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
