name: Internal Relase Build

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-pack:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Prepare
              uses: ./.github/actions/prepare-twizzar

            - name: Rename Namespace and Assebly to TwizzarInternal
              shell: pwsh
              run: |
                  ./BuildScripts/Ci/rename-namespace-for-internal.ps1

            - name: Restore
              uses: ./.github/actions/restore-twizzar
              with:
                  configuration: Internal
                  solution: TwizzarInternal.sln

            - name: Versioning
              id: version
              uses: ./.github/actions/version-twizzar
              with:
                  isInternal: $True

            - name: Build
              uses: ./.github/actions/build-twizzar
              with:
                  configuration: Internal
                  version: ${{ steps.version.outputs.assemblySemVer }}
                  solution: TwizzarInternal.sln

            - name: Publish
              uses: ./.github/actions/publish-twizzar
              with:
                  version: ${{ steps.version.outputs.nuGetVersionV2 }}
                  configuration: Internal
                  projectPrefix: Internal
