name: Relase Build

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build-test-and-pack:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Prepare
              uses: ./.github/actions/prepare-twizzar

            - name: Restore
              uses: ./.github/actions/restore-twizzar
              with:
                  configuration: Release

            - name: Versioning
              id: version
              uses: ./.github/actions/version-twizzar
              with:
                  version: 1.0.0

            - name: Build
              uses: ./.github/actions/build-twizzar
              with:
                  configuration: Release
                  version: ${{ steps.version.outputs.assemblySemVer }}

            - name: Test
              uses: ./.github/actions/test-twizzar

            - name: Publish
              uses: ./.github/actions/publish-twizzar
              with:
                  version: ${{ steps.version.outputs.nuGetVersionV2 }}
                  configuration: Release
                  nugetApiKey: ${{ secrets.NUGET_API_KEY }}
