name: Relase Build

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build-test-and-pack:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Prepare
              uses: ./.github/actions/prepare-twizzar

            - name: Rename Namespace and Assebly to TwizzarInternal
              shell: pwsh
              run: |
                  ./BuildScripts/Ci/rename-namespace-for-internal.ps1

            - name: Restore
              uses: ./.github/actions/restore-twizzar
              with:
                  configuration: Release

            - name: Versioning
              id: version
              uses: ./.github/actions/version-twizzar
              with:
                  version: 1.0.0

            - name: Build
              uses: ./.github/actions/build-twizzar
              with:
                  configuration: Release
                  version: ${{ steps.version.outputs.assemblySemVer }}

            - name: Test
              uses: ./.github/actions/test-twizzar

            - name: Pack
              run: dotnet pack --configuration Release --no-build --output nupkgs /p:PackageVersion=${{ steps.version.outputs.nuGetVersionV2 }}

            - name: Push to NuGet
              run: dotnet nuget push ./**/nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

            - name: Upload Vsix and NuPkg
              uses: actions/upload-artifact@v3
              with:
                  name: Twizzar ${{ steps.version.outputs.nuGetVersionV2 }}
                  path: |
                      **\bin\$(BuildConfiguration)\**\*.vsix
                      **\bin\$(BuildConfiguration)\**\*.nupkg
                  retention-days: 5
