name: Relase Build

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: "5.x"

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.assemblySemVer }}

            - name: Test
              run: dotnet test --configuration Release --no-build --verbosity normals

            - name: Pack
              run: dotnet pack --configuration Release --no-build --output nupkgs /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

            - name: Push to NuGet
              run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
