name: Relase Build

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build-test-and-pack:
        runs-on: windows-2022
        defaults:
            run:
                working-directory: ./Source

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup VSTest
              uses: darenm/Setup-VSTest@v1

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: "5.x"

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.10.2

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1

            - name: Restore NuGet packages
              run: msbuild -t:Restore Twizzar.sln

            - name: Build solution
              run: msbuild Twizzar.sln /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.assemblySemVer }}

            - name: Test
              run: dotnet test --configuration Release --no-build --verbosity normal

            - name: Pack
              run: dotnet pack --configuration Release --no-build --output nupkgs /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

            - name: Push to NuGet
              run: dotnet nuget push ./**/nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

            - name: Upload Vsix and NuPkg
              uses: actions/upload-artifact@v3
              with:
                  name: Twizzar ${{ steps.gitversion.outputs.nuGetVersionV2 }}
                  path: |
                      **\bin\$(BuildConfiguration)\**\*.vsix
                      **\bin\$(BuildConfiguration)\**\*.nupkg
                  retention-days: 5
