// <auto-generated />
using PotionDeliveryService.Interfaces;
using Twizzar.Fixture;
using PotionDeliveryService;

namespace PotionDeliveryService.Tests
{
    partial class DeliveryServiceTests
    {
        private class DeliveryServiceaa96Builder : ItemBuilder<PotionDeliveryService.DeliveryService, DeliveryServiceaa96BuilderPaths>
        {
            public DeliveryServiceaa96Builder()
            {
                this.With(p => p.Ctor.potionRecipes.Stub<IPotionRecipes>());
                this.With(p => p.Ctor.potionRecipes.GetPotionRecipe__String.InstanceOf<ValueTuple<IIngredient, IIngredient>>());
                this.With(p => p.Ctor.potionRecipes.GetPotionRecipe__String.Ctor.item1.Name.Unique());
                this.With(p => p.Ctor.potionRecipes.GetPotionRecipe__String.Ctor.item2.Name.Unique());
                this.With(p => p.Ctor.potionRecipes.GetPotionColor__String.Unique());
                this.With(p => p.Ctor.potionRecipes.GetPotionEffect__String.Stub<IEffect>());
                this.With(p => p.Ctor.potionRecipes.GetPotionEffect__String.Name.Unique());
                this.With(p => p.Ctor.potionRecipes.GetPotionName__IIngredient_IIngredient.Value("MyPotion"));
                this.With(p => p.Ctor.storage.Stub<IStorage>());
                this.With(p => p.Ctor.storage.CheckAvailable__String.Value(true));
                this.With(p => p.Ctor.storage.Take__String.InstanceOf<Potion>());
                this.With(p => p.Ctor.storage.Take__String.Ctor.name.Value("MyPotion"));
                this.With(p =>
                    p.Ctor.packageFactory.CreatePackageT__TIndex.Value<IPotion>(potions => new Package<IPotion>(potions)));
            }
        }

        private class DeliveryServiceBuilder : ItemBuilder<PotionDeliveryService.DeliveryService, DeliveryServiceb88bBuilderPaths>
        {
        }
    }
}