// <auto-generated />
using Twizzar.Fixture;
using PotionDeliveryService.Tests;

namespace PotionDeliveryService.Tests
{
    partial class WorkingWithGenericsTests
    {
        private class IGenericExampleBuilder : ItemBuilder<PotionDeliveryService.Tests.IGenericExample, IGenericExample0397BuilderPaths>
        {
        }
    }
}