// <auto-generated />
using Twizzar.Fixture;
using PotionDeliveryService.Tests;
using PotionDeliveryService.Interfaces;
using System;

namespace PotionDeliveryService.Tests
{
    partial class WorkingWithGenericsTests
    {
        private class IGenericExampleBuilder : ItemBuilder<PotionDeliveryService.Tests.IGenericExample, IGenericExample0397BuilderPaths>
        {
        }

        private class IGenericExample3067Builder : ItemBuilder<PotionDeliveryService.Tests.IGenericExample, IGenericExample3067BuilderPaths>
        {
            public IGenericExample3067Builder()
            {
                this.With(p => p.SimpleGenericMethodT.Stub<IPotion>());
                this.With(p => p.SimpleGenericMethodT.Name.Value("Test"));
                this.With(p => p.MyMethodTItem1TItem2.InstanceOf<ValueTuple<Int32, Single>>());
                this.With(p => p.MyMethodTItem1TItem2.Ctor.item1.Value(1));
                this.With(p => p.MyMethodTItem1TItem2.Ctor.item2.Value(2f));
            }
        }
    }
}