// <auto-generated />
using Twizzar.Fixture;
using PotionDeliveryService.Tests;
using PotionDeliveryService.Interfaces;
using System;

namespace PotionDeliveryService.Tests
{
    partial class WorkingWithGenericsTests
    {
        private class IGenericExampleBuilder : ItemBuilder<PotionDeliveryService.Tests.IGenericExample, IGenericExample0397BuilderPaths>
        {
        }

        private class IGenericExample3067Builder : ItemBuilder<PotionDeliveryService.Tests.IGenericExample, IGenericExample3067BuilderPaths>
        {
            public IGenericExample3067Builder()
            {
                this.With(p => p.MyMethodT.Value(5));
            }
        }
    }
}